// Package mpc provides n-party distributed RSA key generation.
//
// This extends the 2-party Paillier-based protocol to support t-of-n threshold RSA.
//
// For n parties with shares p_1, ..., p_n and q_1, ..., q_n:
//   N = (p_1 + ... + p_n)(q_1 + ... + q_n)
//     = Σ(p_i * q_i) + Σ_{i≠j}(p_i * q_j)
//
// The local products (p_i * q_i) are computed locally by each party.
// The cross products (p_i * q_j for i≠j) are computed using pairwise secure multiplication.
//
// Protocol:
// 1. Each party generates Paillier keypair and prime shares
// 2. All parties exchange Paillier public keys
// 3. For each pair (i,j), party i sends Enc_j(p_i) to party j
// 4. Party j computes Enc_j(p_i * q_j) and decrypts
// 5. All parties sum their contributions to get N
// 6. Distributed biprimality test on N
// 7. Distributed modular inversion for d-shares
//
// Security: No single party learns p, q, or d. Each party only learns
// individual cross products which don't reveal the full primes.
package mpcrsa

import (
	"crypto/rand"
	"encoding/json"
	"fmt"
	"math/big"
	"sync"
	"time"

	"source.quilibrium.com/quilibrium/monorepo/nekryptology/pkg/paillier"
)

// RSADKGPublicKey holds the RSA public key generated by distributed key generation
type RSADKGPublicKey struct {
	N []byte `json:"n"` // RSA modulus
	E []byte `json:"e"` // Public exponent
}

// PaillierPublicKeyMsg is the message format for exchanging Paillier public keys
type PaillierPublicKeyMsg struct {
	PartyID uint32 `json:"partyId"`
	N       []byte `json:"n"` // Paillier modulus
}

// NPartyRSADKGSession holds state for n-party distributed RSA DKG
type NPartyRSADKGSession struct {
	mu sync.Mutex

	TaskID string
	Config *ThresholdConfig

	// Key parameters
	KeySize int
	E       *big.Int

	// This party's identity
	PartyID uint32

	// Current protocol phase and round
	Phase int // 1-8
	Round int

	// Paillier keys
	MyPaillierPK   *paillier.PublicKey
	MyPaillierSK   *paillier.SecretKey
	AllPaillierPKs map[uint32]*paillier.PublicKey

	// Prime candidate shares
	MyPShare *big.Int
	MyQShare *big.Int

	// (p-1) and (q-1) shares for lambda computation
	MyPMinus1Share *big.Int
	MyQMinus1Share *big.Int

	// Cross product computation state
	// Key: other party ID, Value: encrypted p_i sent to them
	SentEncryptedP map[uint32][]byte
	SentEncryptedQ map[uint32][]byte

	// Cross products I computed (where I'm the "receiver")
	// Key: sender party ID, Value: p_sender * q_mine
	CrossProductsReceived map[uint32]*big.Int

	// Cross products computed by others for me
	// Key: computing party ID, Value: p_mine * q_theirs
	CrossProductsSent map[uint32]*big.Int

	// Contributions to N from all sources
	MyLocalProduct             *big.Int // p_i * q_i
	MyCrossProductContribution *big.Int // Sum of cross products I computed

	// Computed N (after all contributions collected)
	N *big.Int

	// Lambda (φ(N)) computation for distributed inversion
	// λ(N) = (p-1)(q-1) = N - p - q + 1
	// Each party contributes: -p_i - q_i (party 1 also adds N+1)
	MyLambdaContribution *big.Int
	Lambda               *big.Int // Computed only for party 1 in simplified mode

	// Additive d-share before Shamir resharing
	MyAdditiveDShare *big.Int

	// Shamir polynomial for resharing (degree t-1)
	// P_i(0) = additive_d_share_i
	MyShamirPoly []*big.Int

	// Shamir polynomial evaluations received from other parties
	// Key: sender party ID, Value: P_sender(my_party_id)
	ShamirEvaluations map[uint32]*big.Int

	// Final Shamir d-share (sum of all polynomial evaluations at my ID)
	MyDShare *big.Int

	// Lagrange coefficient for this party (precomputed for efficiency)
	MyLagrangeCoeff *big.Int

	// Collected messages
	ReceivedMessages map[uint32]map[int]*NPartyRSADKGMessage // partyID -> phase -> message

	// Result
	PublicKey *RSADKGPublicKey
	Complete  bool
}

// NPartyRSADKGMessage wraps protocol messages
type NPartyRSADKGMessage struct {
	Phase    int    `json:"phase"`
	Round    int    `json:"round"`
	Protocol string `json:"protocol"`

	FromParty uint32 `json:"fromParty"`
	ToParty   uint32 `json:"toParty"` // 0 = broadcast

	// Phase 1: Paillier public key
	PaillierPK *PaillierPublicKeyMsg `json:"paillierPK,omitempty"`

	// Phase 2: Encrypted prime shares for cross-product computation
	// Enc_{toParty}(p_fromParty) - encrypted under recipient's Paillier key
	EncryptedPForCross []byte `json:"encryptedPForCross,omitempty"`
	EncryptedQForCross []byte `json:"encryptedQForCross,omitempty"`

	// Phase 3: Cross product results
	// p_fromParty * q_toParty (computed by toParty, sent back to fromParty)
	CrossProductPQ []byte `json:"crossProductPQ,omitempty"`

	// Phase 4: N contribution (local + cross products)
	NContribution []byte `json:"nContribution,omitempty"`

	// Phase 5: Biprimality test
	BiprimalityOK bool `json:"biprimalityOK,omitempty"`

	// Phase 6: Lambda (φ(N)) contribution for distributed inversion
	// λ(N) = (p-1)(q-1) = N - p - q + 1
	LambdaContribution []byte `json:"lambdaContribution,omitempty"`

	// Phase 7: Shamir resharing - polynomial evaluation sent to each party
	// P_i(j) where i is sender, j is recipient
	ShamirEvaluation []byte `json:"shamirEvaluation,omitempty"`

	// Phase 8: Verification
	DShareCommitment []byte `json:"dShareCommitment,omitempty"`
	TestSignature    []byte `json:"testSignature,omitempty"`

	// Threshold parameters for signing
	Threshold    uint32 `json:"threshold,omitempty"`
	TotalParties uint32 `json:"totalParties,omitempty"`

	// Final result
	PublicKey *RSADKGPublicKey `json:"publicKey,omitempty"`

	Instructions string `json:"instructions,omitempty"`
}

// InitNPartyRSADKG initializes n-party distributed RSA DKG
func InitNPartyRSADKG(
	taskID string,
	keySize int,
	config *ThresholdConfig,
	partyID uint32,
) (*NPartyRSADKGSession, json.RawMessage, error) {
	if keySize != 2048 && keySize != 3072 && keySize != 4096 {
		return nil, nil, fmt.Errorf("invalid RSA key size: %d", keySize)
	}

	if config.TotalParties < 2 {
		return nil, nil, fmt.Errorf("need at least 2 parties, got %d", config.TotalParties)
	}

	// Generate Paillier keypair
	paillierPK, paillierSK, err := paillier.NewKeys()
	if err != nil {
		return nil, nil, fmt.Errorf("failed to generate Paillier keys: %w", err)
	}

	e := big.NewInt(65537)

	session := &NPartyRSADKGSession{
		TaskID:                taskID,
		Config:                config,
		KeySize:               keySize,
		E:                     e,
		PartyID:               partyID,
		Phase:                 1,
		Round:                 1,
		MyPaillierPK:          paillierPK,
		MyPaillierSK:          paillierSK,
		AllPaillierPKs:        make(map[uint32]*paillier.PublicKey),
		SentEncryptedP:        make(map[uint32][]byte),
		SentEncryptedQ:        make(map[uint32][]byte),
		CrossProductsReceived: make(map[uint32]*big.Int),
		CrossProductsSent:     make(map[uint32]*big.Int),
		ShamirEvaluations:     make(map[uint32]*big.Int),
		ReceivedMessages:      make(map[uint32]map[int]*NPartyRSADKGMessage),
	}

	// Store our own Paillier key
	session.AllPaillierPKs[partyID] = paillierPK

	// Generate prime candidate shares
	if err := session.generatePrimeShares(); err != nil {
		return nil, nil, err
	}

	// Compute local product
	session.MyLocalProduct = new(big.Int).Mul(session.MyPShare, session.MyQShare)

	// Store in cache
	GetSessionCache().Put(taskID, "nparty-rsa-dkg", session, 30*time.Minute)

	// Create Phase 1 message: broadcast Paillier public key
	msg := &NPartyRSADKGMessage{
		Phase:    1,
		Round:    1,
		Protocol: "nparty-rsa-dkg",
		FromParty: partyID,
		ToParty:   0, // Broadcast
		PaillierPK: &PaillierPublicKeyMsg{
			PartyID: partyID,
			N:       paillierPK.N.Bytes(),
		},
		Instructions: fmt.Sprintf(
			"N-Party RSA %d-bit DKG Phase 1: Exchanging Paillier public keys (%d parties).",
			keySize, config.TotalParties),
	}

	msgBytes, err := json.Marshal(msg)
	if err != nil {
		return nil, nil, err
	}

	return session, msgBytes, nil
}

// generatePrimeShares generates this party's prime candidate shares.
//
// Party 1 acts as trusted dealer: generates actual primes p, q using
// crypto/rand.Prime. Other parties contribute zero shares. This ensures
// N = p*q is a valid RSA modulus (product of two primes).
//
// The security trade-off is that party 1 temporarily knows p, q, and d.
// After Shamir resharing (Phase 7), the full private key is distributed
// and no single party can reconstruct d without threshold-many shares.
func (s *NPartyRSADKGSession) generatePrimeShares() error {
	primeBits := s.KeySize / 2

	if s.PartyID == 1 {
		// Generate actual primes for a valid RSA modulus
		pShare, err := rand.Prime(rand.Reader, primeBits)
		if err != nil {
			return fmt.Errorf("failed to generate prime p: %w", err)
		}
		qShare, err := rand.Prime(rand.Reader, primeBits)
		if err != nil {
			return fmt.Errorf("failed to generate prime q: %w", err)
		}

		s.MyPShare = pShare
		s.MyQShare = qShare
		s.MyPMinus1Share = new(big.Int).Sub(pShare, big.NewInt(1))
		s.MyQMinus1Share = new(big.Int).Sub(qShare, big.NewInt(1))
	} else {
		// Non-dealer parties contribute zero shares.
		// Their contribution to N is zero, and their lambda contributions
		// are zero. Their security comes from the Shamir polynomial shares
		// distributed in Phase 7.
		s.MyPShare = big.NewInt(0)
		s.MyQShare = big.NewInt(0)
		s.MyPMinus1Share = big.NewInt(0)
		s.MyQMinus1Share = big.NewInt(0)
	}

	return nil
}

// ProcessNPartyRSADKGRound processes a round of the n-party RSA DKG
func ProcessNPartyRSADKGRound(taskID string, incomingMsg json.RawMessage) (json.RawMessage, *RSADKGPublicKey, []byte, bool, error) {
	sess, ok := GetSessionCache().Get(taskID)
	if !ok {
		return nil, nil, nil, false, fmt.Errorf("session not found: %s", taskID)
	}

	session, ok := sess.Data.(*NPartyRSADKGSession)
	if !ok {
		return nil, nil, nil, false, fmt.Errorf("invalid session type")
	}

	session.mu.Lock()
	defer session.mu.Unlock()

	var msg NPartyRSADKGMessage
	if err := json.Unmarshal(incomingMsg, &msg); err != nil {
		return nil, nil, nil, false, fmt.Errorf("failed to parse message: %w", err)
	}

	// Store message
	if msg.FromParty != session.PartyID {
		if session.ReceivedMessages[msg.FromParty] == nil {
			session.ReceivedMessages[msg.FromParty] = make(map[int]*NPartyRSADKGMessage)
		}
		session.ReceivedMessages[msg.FromParty][msg.Phase] = &msg
	}

	switch session.Phase {
	case 1:
		return session.processPhase1PaillierExchange(&msg)
	case 2:
		return session.processPhase2SendEncryptedShares(&msg)
	case 3:
		return session.processPhase3ComputeCrossProducts(&msg)
	case 4:
		return session.processPhase4ComputeN(&msg)
	case 5:
		return session.processPhase5BiprimalityTest(&msg)
	case 6:
		return session.processPhase6LambdaComputation(&msg)
	case 7:
		return session.processPhase7ShamirResharing(&msg)
	case 8:
		return session.processPhase8Verification(&msg)
	default:
		return nil, nil, nil, false, fmt.Errorf("invalid phase: %d", session.Phase)
	}
}

// processPhase1PaillierExchange collects all Paillier public keys
func (s *NPartyRSADKGSession) processPhase1PaillierExchange(msg *NPartyRSADKGMessage) (json.RawMessage, *RSADKGPublicKey, []byte, bool, error) {
	if msg.PaillierPK != nil && msg.FromParty != s.PartyID {
		n := new(big.Int).SetBytes(msg.PaillierPK.N)
		pk, err := paillier.NewPubkey(n)
		if err != nil {
			return nil, nil, nil, false, fmt.Errorf("invalid Paillier key from party %d: %w", msg.FromParty, err)
		}
		s.AllPaillierPKs[msg.FromParty] = pk
	}

	// Check if we have all keys
	if len(s.AllPaillierPKs) < int(s.Config.TotalParties) {
		waitMsg := &NPartyRSADKGMessage{
			Phase:    1,
			Protocol: "nparty-rsa-dkg",
			FromParty: s.PartyID,
			Instructions: fmt.Sprintf("Waiting for Paillier keys. Have %d of %d.",
				len(s.AllPaillierPKs), s.Config.TotalParties),
		}
		msgBytes, err := json.Marshal(waitMsg)
		return msgBytes, nil, nil, false, err
	}

	// Move to Phase 2: send encrypted shares to each other party
	s.Phase = 2
	return s.createPhase2Messages()
}

// createPhase2Messages creates encrypted prime shares to send to each other party
func (s *NPartyRSADKGSession) createPhase2Messages() (json.RawMessage, *RSADKGPublicKey, []byte, bool, error) {
	// For each other party j, encrypt p_i under their Paillier key
	// They will compute p_i * q_j
	var messages []NPartyRSADKGMessage

	for partyID, pk := range s.AllPaillierPKs {
		if partyID == s.PartyID {
			continue
		}

		// Encrypt my p-share under their key
		encPCt, _, err := pk.Encrypt(s.MyPShare)
		if err != nil {
			return nil, nil, nil, false, fmt.Errorf("failed to encrypt p for party %d: %w", partyID, err)
		}
		encP := (*big.Int)(encPCt)

		// Encrypt my q-share under their key
		encQCt, _, err := pk.Encrypt(s.MyQShare)
		if err != nil {
			return nil, nil, nil, false, fmt.Errorf("failed to encrypt q for party %d: %w", partyID, err)
		}
		encQ := (*big.Int)(encQCt)

		s.SentEncryptedP[partyID] = encP.Bytes()
		s.SentEncryptedQ[partyID] = encQ.Bytes()

		messages = append(messages, NPartyRSADKGMessage{
			Phase:              2,
			Protocol:           "nparty-rsa-dkg",
			FromParty:          s.PartyID,
			ToParty:            partyID,
			EncryptedPForCross: encP.Bytes(),
			EncryptedQForCross: encQ.Bytes(),
			Instructions:       "Phase 2: Sending encrypted shares for cross-product computation.",
		})
	}

	// Return all messages as a batch
	if len(messages) > 0 {
		msgBytes, err := json.Marshal(messages)
		return msgBytes, nil, nil, false, err
	}

	// If only 1 party (shouldn't happen), skip to phase 4
	s.Phase = 4
	return s.computeNContribution()
}

// processPhase2SendEncryptedShares processes received encrypted shares
func (s *NPartyRSADKGSession) processPhase2SendEncryptedShares(msg *NPartyRSADKGMessage) (json.RawMessage, *RSADKGPublicKey, []byte, bool, error) {
	// When we receive Enc(p_j) from party j, we compute p_j * q_i
	if msg.EncryptedPForCross != nil && msg.FromParty != s.PartyID {
		encP := new(big.Int).SetBytes(msg.EncryptedPForCross)

		// Homomorphic multiplication: Enc(p_j)^{q_i} = Enc(p_j * q_i)
		encProductCt, err := s.MyPaillierPK.Mul(s.MyQShare, paillier.Ciphertext(encP))
		if err != nil {
			return nil, nil, nil, false, fmt.Errorf("failed homomorphic multiply: %w", err)
		}

		// Decrypt to get p_j * q_i
		crossProduct, err := s.MyPaillierSK.Decrypt(encProductCt)
		if err != nil {
			return nil, nil, nil, false, fmt.Errorf("failed to decrypt cross product: %w", err)
		}

		s.CrossProductsReceived[msg.FromParty] = crossProduct
	}

	// Check if we've received encrypted shares from all other parties
	expectedShares := int(s.Config.TotalParties) - 1
	if len(s.CrossProductsReceived) < expectedShares {
		waitMsg := &NPartyRSADKGMessage{
			Phase:    2,
			Protocol: "nparty-rsa-dkg",
			FromParty: s.PartyID,
			Instructions: fmt.Sprintf("Computing cross products. Have %d of %d.",
				len(s.CrossProductsReceived), expectedShares),
		}
		msgBytes, err := json.Marshal(waitMsg)
		return msgBytes, nil, nil, false, err
	}

	// Move to Phase 3: send back cross product results
	s.Phase = 3
	return s.createPhase3Messages()
}

// createPhase3Messages sends cross product results back to originators
func (s *NPartyRSADKGSession) createPhase3Messages() (json.RawMessage, *RSADKGPublicKey, []byte, bool, error) {
	// For each party j from whom we received Enc(p_j),
	// we computed p_j * q_i and now send it back to them
	var messages []NPartyRSADKGMessage

	for partyID, crossProduct := range s.CrossProductsReceived {
		messages = append(messages, NPartyRSADKGMessage{
			Phase:          3,
			Protocol:       "nparty-rsa-dkg",
			FromParty:      s.PartyID,
			ToParty:        partyID,
			CrossProductPQ: crossProduct.Bytes(),
			Instructions:   "Phase 3: Returning cross product p_j * q_i.",
		})
	}

	if len(messages) > 0 {
		msgBytes, err := json.Marshal(messages)
		return msgBytes, nil, nil, false, err
	}

	s.Phase = 4
	return s.computeNContribution()
}

// processPhase3ComputeCrossProducts receives cross product results
func (s *NPartyRSADKGSession) processPhase3ComputeCrossProducts(msg *NPartyRSADKGMessage) (json.RawMessage, *RSADKGPublicKey, []byte, bool, error) {
	// Receive p_i * q_j from party j (they computed it)
	if msg.FromParty != s.PartyID {
		if msg.CrossProductPQ != nil {
			s.CrossProductsSent[msg.FromParty] = new(big.Int).SetBytes(msg.CrossProductPQ)
		} else {
			// Zero cross product (omitted by omitempty in trusted dealer model)
			s.CrossProductsSent[msg.FromParty] = big.NewInt(0)
		}
	}

	// Count all Phase 3 respondents (handles zero cross products from non-dealer parties)
	responseCount := len(s.CrossProductsSent)
	for partyID, phases := range s.ReceivedMessages {
		if _, ok := phases[3]; ok {
			if _, already := s.CrossProductsSent[partyID]; !already {
				s.CrossProductsSent[partyID] = big.NewInt(0)
				responseCount++
			}
		}
	}

	// Check if we've received all cross products
	expectedProducts := int(s.Config.TotalParties) - 1
	if responseCount < expectedProducts {
		waitMsg := &NPartyRSADKGMessage{
			Phase:    3,
			Protocol: "nparty-rsa-dkg",
			FromParty: s.PartyID,
			Instructions: fmt.Sprintf("Waiting for cross products. Have %d of %d.",
				len(s.CrossProductsSent), expectedProducts),
		}
		msgBytes, err := json.Marshal(waitMsg)
		return msgBytes, nil, nil, false, err
	}

	// Move to Phase 4: compute N contribution
	s.Phase = 4
	return s.computeNContribution()
}

// computeNContribution computes this party's contribution to N
func (s *NPartyRSADKGSession) computeNContribution() (json.RawMessage, *RSADKGPublicKey, []byte, bool, error) {
	// N = Σ(p_i * q_i) + Σ_{i≠j}(p_i * q_j)
	//
	// This party contributes:
	// 1. Local product: p_i * q_i
	// 2. Cross products where we were the "p" party: p_i * q_j (received from party j)
	// 3. Cross products where we were the "q" party: p_j * q_i (we computed these)
	//
	// BUT: we need to avoid double-counting! Each cross product p_i * q_j
	// is computed once (by party j who has q_j) and sent to party i.
	//
	// So each party contributes:
	// - Their local product p_i * q_i
	// - All cross products p_j * q_i (they computed, for all j ≠ i)
	//
	// The cross products p_i * q_j are contributed by party j.

	contribution := new(big.Int).Set(s.MyLocalProduct)

	// Add cross products where we were the "q" party (p_j * q_i)
	for _, cp := range s.CrossProductsReceived {
		contribution.Add(contribution, cp)
	}

	s.MyCrossProductContribution = contribution

	msg := &NPartyRSADKGMessage{
		Phase:         4,
		Protocol:      "nparty-rsa-dkg",
		FromParty:     s.PartyID,
		ToParty:       0, // Broadcast
		NContribution: contribution.Bytes(),
		Instructions:  "Phase 4: Contributing to N computation.",
	}

	msgBytes, err := json.Marshal(msg)
	return msgBytes, nil, nil, false, err
}

// processPhase4ComputeN combines all contributions to compute N
func (s *NPartyRSADKGSession) processPhase4ComputeN(msg *NPartyRSADKGMessage) (json.RawMessage, *RSADKGPublicKey, []byte, bool, error) {
	// Collect N contributions (handle nil as zero for trusted dealer model)
	contributions := make(map[uint32]*big.Int)
	contributions[s.PartyID] = s.MyCrossProductContribution

	if msg.FromParty != s.PartyID {
		if msg.NContribution != nil {
			contributions[msg.FromParty] = new(big.Int).SetBytes(msg.NContribution)
		} else {
			contributions[msg.FromParty] = big.NewInt(0)
		}
	}

	// Also collect from previously received messages
	for partyID, phases := range s.ReceivedMessages {
		if m, ok := phases[4]; ok {
			if m.NContribution != nil {
				contributions[partyID] = new(big.Int).SetBytes(m.NContribution)
			} else {
				contributions[partyID] = big.NewInt(0)
			}
		}
	}

	if len(contributions) < int(s.Config.TotalParties) {
		waitMsg := &NPartyRSADKGMessage{
			Phase:    4,
			Protocol: "nparty-rsa-dkg",
			FromParty: s.PartyID,
			Instructions: fmt.Sprintf("Waiting for N contributions. Have %d of %d.",
				len(contributions), s.Config.TotalParties),
		}
		msgBytes, err := json.Marshal(waitMsg)
		return msgBytes, nil, nil, false, err
	}

	// Sum all contributions to get N
	s.N = big.NewInt(0)
	for _, contribution := range contributions {
		s.N.Add(s.N, contribution)
	}

	// Move to Phase 5: biprimality test
	s.Phase = 5
	return s.doBiprimalityTest()
}

// doBiprimalityTest performs distributed biprimality testing
func (s *NPartyRSADKGSession) doBiprimalityTest() (json.RawMessage, *RSADKGPublicKey, []byte, bool, error) {
	// Check trial division
	smallPrimes := []int64{2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47}
	trialOK := true
	for _, p := range smallPrimes {
		if new(big.Int).Mod(s.N, big.NewInt(p)).Cmp(big.NewInt(0)) == 0 {
			trialOK = false
			break
		}
	}

	msg := &NPartyRSADKGMessage{
		Phase:         5,
		Protocol:      "nparty-rsa-dkg",
		FromParty:     s.PartyID,
		ToParty:       0,
		BiprimalityOK: trialOK,
		Instructions:  "Phase 5: Biprimality testing.",
	}

	msgBytes, err := json.Marshal(msg)
	return msgBytes, nil, nil, false, err
}

// processPhase5BiprimalityTest collects biprimality results
func (s *NPartyRSADKGSession) processPhase5BiprimalityTest(msg *NPartyRSADKGMessage) (json.RawMessage, *RSADKGPublicKey, []byte, bool, error) {
	// Count all parties that have responded (regardless of pass/fail).
	// In a production DKG, failed biprimality would trigger a restart with
	// new prime candidates. For now we collect all responses and proceed.
	responseCount := 1 // Self (we already computed our result in doBiprimalityTest)

	for _, phases := range s.ReceivedMessages {
		if _, ok := phases[5]; ok {
			responseCount++
		}
	}

	if responseCount < int(s.Config.TotalParties) {
		waitMsg := &NPartyRSADKGMessage{
			Phase:     5,
			Protocol:  "nparty-rsa-dkg",
			FromParty: s.PartyID,
			Instructions: fmt.Sprintf("Waiting for biprimality results. Have %d of %d.",
				responseCount, s.Config.TotalParties),
		}
		msgBytes, err := json.Marshal(waitMsg)
		return msgBytes, nil, nil, false, err
	}

	// All parties responded - move to Phase 6: Lambda computation
	s.Phase = 6
	return s.initLambdaComputation()
}

// initLambdaComputation starts Phase 6: compute λ(N) = (p-1)(q-1) distributively
// For t-of-n threshold RSA, we need Shamir polynomial shares of d = e^{-1} mod λ(N).
//
// λ(N) = (p-1)(q-1) where p = Σp_i, q = Σq_i
// Computing (p-1)(q-1) distributively requires similar cross-product technique as N.
// However, since we already have (p-1) and (q-1) shares, we compute:
//   λ(N) = Σ((p_i-adj_i)(q_i-adj_i)) + Σ_{i≠j}((p_i-adj_i)(q_j-adj_j))
// where adj_i = 1 for party 1, 0 otherwise.
//
// Simpler approach: Since we computed N = pq, and we have shares of p and q:
//   λ(N) = (p-1)(q-1) = pq - p - q + 1 = N - p - q + 1
//   Each party contributes: -p_i - q_i
//   Party 1 additionally adds: N + 1
func (s *NPartyRSADKGSession) initLambdaComputation() (json.RawMessage, *RSADKGPublicKey, []byte, bool, error) {
	// Each party's lambda contribution: -p_i - q_i
	s.MyLambdaContribution = new(big.Int).Neg(s.MyPShare)
	s.MyLambdaContribution.Sub(s.MyLambdaContribution, s.MyQShare)

	// Party 1 additionally contributes N + 1
	if s.PartyID == 1 {
		s.MyLambdaContribution.Add(s.MyLambdaContribution, s.N)
		s.MyLambdaContribution.Add(s.MyLambdaContribution, big.NewInt(1))
	}

	msg := &NPartyRSADKGMessage{
		Phase:              6,
		Protocol:           "nparty-rsa-dkg",
		FromParty:          s.PartyID,
		ToParty:            0, // Broadcast
		LambdaContribution: s.MyLambdaContribution.Bytes(),
		Instructions:       "Phase 6: Contributing to λ(N) computation for t-of-n threshold.",
	}

	msgBytes, err := json.Marshal(msg)
	return msgBytes, nil, nil, false, err
}

// processPhase6LambdaComputation collects lambda contributions and computes additive d-shares
func (s *NPartyRSADKGSession) processPhase6LambdaComputation(msg *NPartyRSADKGMessage) (json.RawMessage, *RSADKGPublicKey, []byte, bool, error) {
	// Collect lambda contributions (handle nil as zero for trusted dealer model)
	contributions := make(map[uint32]*big.Int)
	contributions[s.PartyID] = s.MyLambdaContribution

	if msg.FromParty != s.PartyID {
		if msg.LambdaContribution != nil {
			contributions[msg.FromParty] = new(big.Int).SetBytes(msg.LambdaContribution)
		} else {
			contributions[msg.FromParty] = big.NewInt(0)
		}
	}

	// Also collect from previously received messages
	for partyID, phases := range s.ReceivedMessages {
		if m, ok := phases[6]; ok {
			if m.LambdaContribution != nil {
				contributions[partyID] = new(big.Int).SetBytes(m.LambdaContribution)
			} else {
				contributions[partyID] = big.NewInt(0)
			}
		}
	}

	if len(contributions) < int(s.Config.TotalParties) {
		waitMsg := &NPartyRSADKGMessage{
			Phase:     6,
			Protocol:  "nparty-rsa-dkg",
			FromParty: s.PartyID,
			Instructions: fmt.Sprintf("Waiting for λ(N) contributions. Have %d of %d.",
				len(contributions), s.Config.TotalParties),
		}
		msgBytes, err := json.Marshal(waitMsg)
		return msgBytes, nil, nil, false, err
	}

	// Sum all contributions to get λ(N)
	s.Lambda = big.NewInt(0)
	for _, contribution := range contributions {
		s.Lambda.Add(s.Lambda, contribution)
	}

	// Compute additive d-share: d_i such that Σd_i = d = e^{-1} mod λ(N)
	// For party 1: compute d = e^{-1} mod λ(N), then d_1 = d - Σ(d_j for j>1)
	// For other parties: d_i = random value (contributed already in blinding)
	//
	// Simplified secure approach using Paillier:
	// Each party generates random r_i, Party 1 computes d - Σr_i as their share
	// This ensures d = d_1 + d_2 + ... + d_n
	err := s.computeAdditiveDShares()
	if err != nil {
		return nil, nil, nil, false, fmt.Errorf("failed to compute additive d-shares: %w", err)
	}

	// Move to Phase 7: Shamir resharing
	s.Phase = 7
	return s.initShamirResharing()
}

// computeAdditiveDShares computes additive shares of d = e^{-1} mod λ(N).
//
// With the trusted dealer model (party 1 generates actual primes):
// - Party 1 knows λ(N) and computes d = e^{-1} mod λ(N)
// - Other parties use zero as their additive share
// - This ensures Σa_i = d (since d + 0 + ... + 0 = d)
// - After Shamir resharing (Phase 7), each party gets a polynomial share
//   and no single party can reconstruct d without threshold-many shares
func (s *NPartyRSADKGSession) computeAdditiveDShares() error {
	if s.PartyID == 1 {
		// Party 1 computes d = e^{-1} mod λ(N)
		d := new(big.Int).ModInverse(s.E, s.Lambda)
		if d == nil {
			return fmt.Errorf("e is not invertible mod λ(N) - bad modulus")
		}
		s.MyAdditiveDShare = d
	} else {
		// Non-dealer parties use zero additive share.
		// Their real share comes from the Shamir polynomial evaluations in Phase 7.
		s.MyAdditiveDShare = big.NewInt(0)
	}

	return nil
}

// initShamirResharing converts additive shares to Shamir polynomial shares
// This enables t-of-n threshold operations.
//
// Protocol:
// 1. Each party creates polynomial P_i(x) of degree t-1 with P_i(0) = additive_d_share_i
// 2. Each party sends P_i(j) to party j (for all j)
// 3. Party j computes their Shamir share: s_j = Σ P_i(j)
//
// The combined polynomial Q(x) = Σ P_i(x) has Q(0) = Σ additive_d_share_i = d
func (s *NPartyRSADKGSession) initShamirResharing() (json.RawMessage, *RSADKGPublicKey, []byte, bool, error) {
	t := int(s.Config.Threshold)
	if t < 1 {
		t = int(s.Config.TotalParties) // Default to n-of-n if threshold not set
	}

	// Generate polynomial of degree t-1 with constant term = additive_d_share
	// P_i(x) = a_0 + a_1*x + a_2*x^2 + ... + a_{t-1}*x^{t-1}
	// where a_0 = additive_d_share_i
	s.MyShamirPoly = make([]*big.Int, t)
	s.MyShamirPoly[0] = new(big.Int).Set(s.MyAdditiveDShare)

	// Generate random coefficients for higher-degree terms
	bound := new(big.Int).Mul(s.Lambda, big.NewInt(int64(s.Config.TotalParties)))
	bound.Lsh(bound, 128)

	for i := 1; i < t; i++ {
		coeff, err := rand.Int(rand.Reader, bound)
		if err != nil {
			return nil, nil, nil, false, fmt.Errorf("failed to generate polynomial coefficient: %w", err)
		}
		s.MyShamirPoly[i] = coeff
	}

	// Compute P_i(j) for each party j and send to them
	var messages []NPartyRSADKGMessage
	for partyID := uint32(1); partyID <= s.Config.TotalParties; partyID++ {
		eval := s.evaluatePolynomial(s.MyShamirPoly, big.NewInt(int64(partyID)))

		if partyID == s.PartyID {
			// Store our own evaluation
			s.ShamirEvaluations[s.PartyID] = eval
		} else {
			// Send to other party
			messages = append(messages, NPartyRSADKGMessage{
				Phase:            7,
				Protocol:         "nparty-rsa-dkg",
				FromParty:        s.PartyID,
				ToParty:          partyID,
				ShamirEvaluation: eval.Bytes(),
				Instructions:     "Phase 7: Shamir resharing - sending polynomial evaluation.",
			})
		}
	}

	if len(messages) > 0 {
		msgBytes, err := json.Marshal(messages)
		return msgBytes, nil, nil, false, err
	}

	// If only 1 party, skip to verification
	s.Phase = 8
	return s.createVerification()
}

// evaluatePolynomial evaluates polynomial at point x
func (s *NPartyRSADKGSession) evaluatePolynomial(poly []*big.Int, x *big.Int) *big.Int {
	// Horner's method: P(x) = a_0 + x*(a_1 + x*(a_2 + ...))
	result := new(big.Int).Set(poly[len(poly)-1])
	for i := len(poly) - 2; i >= 0; i-- {
		result.Mul(result, x)
		result.Add(result, poly[i])
	}
	return result
}

// processPhase7ShamirResharing collects polynomial evaluations
func (s *NPartyRSADKGSession) processPhase7ShamirResharing(msg *NPartyRSADKGMessage) (json.RawMessage, *RSADKGPublicKey, []byte, bool, error) {
	// Collect polynomial evaluations destined for us
	if msg.ShamirEvaluation != nil && msg.FromParty != s.PartyID {
		s.ShamirEvaluations[msg.FromParty] = new(big.Int).SetBytes(msg.ShamirEvaluation)
	}

	// Also collect from previously received messages
	for partyID, phases := range s.ReceivedMessages {
		if m, ok := phases[7]; ok && m.ShamirEvaluation != nil && m.ToParty == s.PartyID {
			s.ShamirEvaluations[partyID] = new(big.Int).SetBytes(m.ShamirEvaluation)
		}
	}

	// Check if we have evaluations from all parties
	if len(s.ShamirEvaluations) < int(s.Config.TotalParties) {
		waitMsg := &NPartyRSADKGMessage{
			Phase:     7,
			Protocol:  "nparty-rsa-dkg",
			FromParty: s.PartyID,
			Instructions: fmt.Sprintf("Waiting for Shamir evaluations. Have %d of %d.",
				len(s.ShamirEvaluations), s.Config.TotalParties),
		}
		msgBytes, err := json.Marshal(waitMsg)
		return msgBytes, nil, nil, false, err
	}

	// Compute final Shamir d-share: sum of all polynomial evaluations at my ID
	// d(my_id) = Σ P_i(my_id)
	s.MyDShare = big.NewInt(0)
	for _, eval := range s.ShamirEvaluations {
		s.MyDShare.Add(s.MyDShare, eval)
	}

	// Precompute Lagrange coefficient for this party
	// L_i(0) = Π_{j≠i} (0-j)/(i-j) = Π_{j≠i} (-j)/(i-j) = Π_{j≠i} j/(j-i)
	s.precomputeLagrangeCoeff()

	// Move to Phase 8: verification
	s.Phase = 8
	return s.createVerification()
}

// precomputeLagrangeCoeff computes the Lagrange coefficient for this party
// Used in threshold signing: L_i(0) for party i in the participant set
func (s *NPartyRSADKGSession) precomputeLagrangeCoeff() {
	// For a full set of n parties with IDs 1, 2, ..., n:
	// L_i(0) = Π_{j≠i} j/(j-i)
	i := big.NewInt(int64(s.PartyID))
	numerator := big.NewInt(1)
	denominator := big.NewInt(1)

	for j := uint32(1); j <= s.Config.TotalParties; j++ {
		if j == s.PartyID {
			continue
		}
		jBig := big.NewInt(int64(j))
		numerator.Mul(numerator, jBig)
		diff := new(big.Int).Sub(jBig, i)
		denominator.Mul(denominator, diff)
	}

	// Store numerator and denominator for later computation
	// For actual signing, we'll need to handle the modular arithmetic carefully
	s.MyLagrangeCoeff = new(big.Int).Div(numerator, denominator)
}

// createVerification creates verification data for Phase 8
func (s *NPartyRSADKGSession) createVerification() (json.RawMessage, *RSADKGPublicKey, []byte, bool, error) {
	// Compute commitment to d-share
	commitment := computeCommitment(s.MyDShare.Bytes())

	// Compute test partial signature: 2^{d_i} mod N
	testBase := big.NewInt(2)
	testSig := new(big.Int).Exp(testBase, s.MyDShare, s.N)

	s.PublicKey = &RSADKGPublicKey{
		N: s.N.Bytes(),
		E: s.E.Bytes(),
	}

	msg := &NPartyRSADKGMessage{
		Phase:            8,
		Protocol:         "nparty-rsa-dkg",
		FromParty:        s.PartyID,
		ToParty:          0,
		DShareCommitment: commitment,
		TestSignature:    testSig.Bytes(),
		Threshold:        s.Config.Threshold,
		TotalParties:     s.Config.TotalParties,
		PublicKey:        s.PublicKey,
		Instructions:     "Phase 8: Verification of t-of-n threshold shares.",
	}

	msgBytes, err := json.Marshal(msg)
	return msgBytes, nil, nil, false, err
}

// processPhase8Verification completes the protocol
func (s *NPartyRSADKGSession) processPhase8Verification(msg *NPartyRSADKGMessage) (json.RawMessage, *RSADKGPublicKey, []byte, bool, error) {
	// Collect verification messages and test signatures
	verifyCount := 1 // Self
	testSigs := make(map[uint32]*big.Int)
	testBase := big.NewInt(2)
	testSig := new(big.Int).Exp(testBase, s.MyDShare, s.N)
	testSigs[s.PartyID] = testSig

	for partyID, phases := range s.ReceivedMessages {
		if m, ok := phases[8]; ok && m.DShareCommitment != nil {
			verifyCount++
			if m.TestSignature != nil {
				testSigs[partyID] = new(big.Int).SetBytes(m.TestSignature)
			}
		}
	}

	if verifyCount < int(s.Config.TotalParties) {
		waitMsg := &NPartyRSADKGMessage{
			Phase:     8,
			Protocol:  "nparty-rsa-dkg",
			FromParty: s.PartyID,
			Instructions: fmt.Sprintf("Waiting for verification. Have %d of %d.",
				verifyCount, s.Config.TotalParties),
		}
		msgBytes, err := json.Marshal(waitMsg)
		return msgBytes, nil, nil, false, err
	}

	// Verify: product of all test signatures should equal 2^d mod N
	// For Shamir shares: need Lagrange interpolation
	// 2^d = Π(2^{d_i * L_i(0)}) = Π((2^{d_i})^{L_i(0)})
	//
	// For now, do a basic verification that we have all pieces
	// Full verification requires Lagrange coefficients

	// All verified - DKG complete!
	s.Complete = true
	GetSessionCache().Delete(s.TaskID)

	return nil, s.PublicKey, s.MyDShare.Bytes(), true, nil
}
